localdb:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=localdb_username
    - POSTGRES_PASSWORD=localdb_password
    - POSTGRES_DB=localdb_name

testdb:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=testdb_username
    - POSTGRES_PASSWORD=testdb_password
    - POSTGRES_DB=testdb_name